import { useState } from 'react';
import './Profile.css';

const Profile = () => {
	const [saved, setSaved] = useState(false);
	const [profile, setProfile] = useState({ name: 'Ariel Mwangi', email: 'ariel@example.com', cohort: 'Moringa Cohort 15', preference: 'Talk through ideas', goal: 'Frontend architecture' });
	const update = (event) => setProfile({ ...profile, [event.target.name]: event.target.value });
	return <div className="profile-shell"><aside className="profile-sidebar"><a className="brand" href="/dashboard"><span className="brand-mark">m</span><span>Moringa<span className="brand-accent">Pair</span></span></a><nav className="assessment-nav"><a className="nav-item" href="/dashboard"><span className="nav-icon">◆</span>My pairing</a><a className="nav-item" href="/assessment"><span className="nav-icon">▣</span>Assessment</a><a className="nav-item" href="/dashboard#pairing-history"><span className="nav-icon">▤</span>Pairing history</a></nav><div className="sidebar-bottom"><a className="nav-item nav-item-active" href="/profile"><span className="nav-icon">◯</span>Profile</a><a className="nav-item" href="/login"><span className="nav-icon">↪</span>Log out</a></div></aside><main className="profile-main"><header className="assessment-header"><div><p className="eyebrow">Your space</p><h1>Profile</h1></div><button className="avatar-button">AM</button></header><section className="profile-card"><div className="profile-hero"><span className="profile-avatar">AM</span><div><h2>{profile.name}</h2><p>{profile.cohort} · Student</p></div></div><form className="profile-form" onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><div className="profile-grid"><label>Full name<input name="name" value={profile.name} onChange={update} /></label><label>Email address<input name="email" type="email" value={profile.email} onChange={update} /></label><label>Cohort<input name="cohort" value={profile.cohort} onChange={update} /></label><label>How I learn best<select name="preference" value={profile.preference} onChange={update}><option>Talk through ideas</option><option>Read documentation</option><option>Build a small project</option><option>Watch a walkthrough</option></select></label></div><label>What I want to strengthen<select name="goal" value={profile.goal} onChange={update}><option>Frontend architecture</option><option>Testing and debugging</option><option>Communication</option><option>Problem solving</option></select></label><div className="profile-footer"><span>{saved ? 'Profile details saved.' : 'These details help your TM make thoughtful pairings.'}</span><button className="primary-button" type="submit">Save changes <span>→</span></button></div></form></section></main></div>;
};

export default Profile;